language: ruby
rvm:
 - "2.3.x"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec jekyll build
git:
  depth: 3
install:
  - bundle install --path .vendor/bundle