name: Your New Jekyll Site
pygments: true
destination: ../../Sites/my-jekyll-site-html
permalink: /blog/:categories/:title
paginate: 5
paginate_path: "/blog/:num"
markdown: redcarpet

picture:
  source: ""
  output: "generated"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 2]
      attr:
        class: "picture--default"
        itemprop: "image"
      source_huge:
        media: "(min-width: 1025px)"
        width: "1400"
      source_big:
        media: "(min-width: 750px)"
        width: "1025"
      source_medium:
        media: "(min-width: 500px)"
        width: "750"
      source_default: 
        width: "480"

JB:
  BASE_PATH : /
  categories_path : /blog/categories.html
  tags_path : /blog/tags.html
