name: Evan Lovely's Site
description: "The blog of Front End Drupal Developer, Photographer, Traveler and Nature Enthusiast Evan Lovely."
author: 
  name: Evan Lovely
  email: evan@evanlovely.com
header_img: glacier
url: http://evanlovely.com
github: https://github.com/EvanLovely/my-jekyll-site/commits/master
#highlighter: pygments
destination: ../my-jekyll-site-html/
permalink: /blog/:categories/:title
paginate: 10
paginate_path: "/blog/page/:num"
#markdown: redcarpet
keep_files:
  - "generated"
exclude: 
  - node_modules
  - grunt-tasks
  - rsync-log.txt
  - Gruntfile.js
  - Gruntconfig.yml
  - Gemfil*
  - bower.json
  - package.json
  - pattern-lab-assets.yml
collections:
  blogposts:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "blogposts"
    values:
      layout: "post"
      categories: Technology


gems:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-paginate

picture:
  source: ""
  output: "generated"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 2]
      attr:
        class: "picture--default"
        itemprop: "image"
      source_huge:
        media: "(min-width: 1025px)"
        width: "1368"
      source_big:
        media: "(min-width: 896px)"
        width: "1025"
      source_large:
        media: "(min-width: 600px)"
        width: "642"
      source_medium:
        media: "(min-width: 340px)"
        width: "568"
      source_default: 
        width: "300"
    blog:
      ppi: [1, 2]
      attr:
        class: "picture--blog"
        itemprop: "image"
      source_huge:
        media: "(min-width: 1388px)"
        width: "821"
      source_big:
        media: "(min-width: 750px)"
        width: "630"
      source_medium:
        media: "(min-width: 340px)"
        width: "568"
      source_default: 
        width: "300"
    aside:
      ppi: [1, 2]
      attr:
        class: "picture--aside"
        itemprop: "image"
      source_huge:
        media: "(min-width: 1388px)"
        width: "521"
      source_big:
        media: "(min-width: 750px)"
        width: "430"
      source_medium:
        media: "(min-width: 340px)"
        width: "568"
      source_default: 
        width: "300"
    third:
      ppi: [1, 2]
      attr:
        class: "picture--third"
        itemprop: "image"
      source_huge:
        media: "(min-width: 1388px)"
        width: "521"
      source_big:
        media: "(min-width: 600px)"
        width: "430"
      source_medium:
        media: "(min-width: 440px)"
        width: "568"
      source_default: 
        width: "300"

JB:
  BASE_PATH : /
  categories_path : /blog/categories.html
  tags_path : /blog/tags.html
