name: Your New Jekyll Site
pygments: true
destination: ../../Sites/my-jekyll-site-html
permalink: /:categories/:title
paginate: 5
paginate_path: "/blog/:num"

JB:
  BASE_PATH : /
  categories_path : /blog/categories.html
  tags_path : /blog/tags.html
