css:
  enabled: true
  src:
    - src/**/*.scss
  dest: dist/assets
  flattenDestOutput: true
  lint:
    enabled: true
    failOnError: true
    # Add to the main src glob - useful for exclusions with `!`
#    extraSrc:
#      - '!src/scss/00-config/02-variables/_typography.scss'
  # enables additional debugging information in the output file as CSS comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: expanded
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 10
  includePaths:
    - ./node_modules
  sassdoc: # http://sassdoc.com
    enabled: true
    dest: dist/assets/sassdoc
    verbose: false
    basePath: http://github.com/evanlovely/my-site
#    exclude:
#      - file.scss
    theme: default
    sort: # http://sassdoc.com/customising-the-view/#sort
      - file
      - group
      - line>
js:
  enabled: false
  src:
    - src/js/**/*.js
  dest: dest/
  destName: all.min.js
  sourceMapEmbed: false
  uglify: false
  babel: false
  eslint:
    enabled: true
    src:
      - src/js/**/*.js
      - gulpfile.js
patternLab:
  enabled: false
  src:
    data: src/data/
    patternLabFiles: src/patternlab-files/
    patterns: src/patterns/
  dest: dest/pattern-lab/
#  config: config--pattern-lab.json # WIP - do not enable
  injectFiles:
#    - bower_components/modernizr/modernizr.js
  injectBower: true
icons: # https://github.com/nfroidure/gulp-iconfont
  enabled: false
  src: src/images/icons/src/*.svg
  dest: dest/
  fontPathPrefix: ''
  classNamePrefix: icon
  autohint: false
  normalize: true
  templates:
    enabled: true
    css:
      src: src/images/icons/templates/_icons.scss
      dest: src/scss/00-config/
    demo:
      src: src/images/icons/templates/icons.mustache
      dest: src/patterns/00-atoms/04-images/
  formats:
    - ttf
    - eot
    - woff
    - svg
browserSync:
  enabled: true
  port: 3042
  watchFiles:
    # - template.php
  # domain: mysite.dev # enable when full CMS is set up
  baseDir: ./dist
  startPath: 
  openBrowserAtStart: true
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome Canary
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
  tunnel: false
  reloadDelay: 50
  reloadDebounce: 750
drupal:
  enabled: false
